BACKGROUND = "#222"
BACKGROUND_RGB = "rgb(34, 34, 34)"

COUNTY_MAX_VAL = 0xFF
COUNTY_MIN_VAL = 0xAA
MARGINAL = 0.001

COUNTY_MAX_GOP = "#f00"
COUNTY_MIN_GOP = "#faa"
EVEN = "#fff"
COUNTY_MAX_DEM = "#00f"
COUNTY_MIN_DEM = "#aaf"

COUNTY_COLORSCALE = [
    [0, COUNTY_MAX_GOP],
    [0.5 - MARGINAL, COUNTY_MIN_GOP],
    [0.5, EVEN],
    [0.5 + MARGINAL, COUNTY_MIN_DEM],
    [1.0, COUNTY_MAX_DEM],
]

STATE_GOP_CLOSE = "#ffb3b3"
STATE_DEM_CLOSE = "#b3b3ff"

STATE_GOP_BATTLEGROUND = "#ff8080"
STATE_DEM_BATTLEGROUND = "#8080ff"

STATE_GOP = "#ff4d4d"
STATE_DEM = "#4d4dff"

TEXT_COLOR = "white"
